# Generated by Django 2.2.1 on 2019-05-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing', models.ImageField(default='', upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('usr', models.CharField(max_length=30)),
            ],
        ),
    ]
