# Generated by Django 2.2.1 on 2019-05-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='usr',
        ),
    ]
