# Generated by Django 2.2.1 on 2019-05-06 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0002_auto_20190506_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
