# Generated by Django 2.2.1 on 2019-05-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0005_auto_20190507_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='drawing',
            field=models.TextField(),
        ),
    ]
